use crate::metatype::types::*;

pub struct MetatypeBuilder {
    name: String,
    body_min: i32,
    body_max: i32,
    agility_min: i32,
    agility_max: i32,
    reaction_min: i32,
    reaction_max: i32,
    strength_min: i32,
    strength_max: i32,
    willpower_min: i32,
    willpower_max: i32,
    logic_min: i32,
    logic_max: i32,
    intuition_min: i32,
    intuition_max: i32,
    charisma_min: i32,
    charisma_max: i32,
    edge_min: i32,
    edge_max: i32,
    magical_type: MagicalType,
    magic_min: i32,
    magic_max: i32,
    resonance_min: i32,
    resonance_max: i32,
}

#[allow(dead_code)]
impl MetatypeBuilder {
    pub fn new() -> Self {
        Self {
            name: String::new(),
            body_min: 1,
            body_max: 6,
            agility_min: 1,
            agility_max: 6,
            reaction_min: 1,
            reaction_max: 6,
            strength_min: 1,
            strength_max: 6,
            willpower_min: 1,
            willpower_max: 6,
            logic_min: 1,
            logic_max: 6,
            intuition_min: 1,
            intuition_max: 6,
            charisma_min: 1,
            charisma_max: 6,
            edge_min: 1,
            edge_max: 6,
            magical_type: MagicalType::Mundane,
            magic_min: 0,
            magic_max: 0,
            resonance_min: 0,
            resonance_max: 0,
        }
    }

    pub fn build(self) -> Metatype {
        Metatype {
            id: None,
            name: self.name,
            body_min: self.body_min,
            body_max: self.body_max,
            agility_min: self.agility_min,
            agility_max: self.agility_max,
            reaction_min: self.reaction_min,
            reaction_max: self.reaction_max,
            strength_min: self.strength_min,
            strength_max: self.strength_max,
            willpower_min: self.willpower_min,
            willpower_max: self.willpower_max,
            logic_min: self.logic_min,
            logic_max: self.logic_max,
            intuition_min: self.intuition_min,
            intuition_max: self.intuition_max,
            charisma_min: self.charisma_min,
            charisma_max: self.charisma_max,
            edge_min: self.edge_min,
            edge_max: self.edge_max,
            magical_type: self.magical_type,
            magic_min: self.magic_min,
            magic_max: self.magic_max,
            resonance_min: self.resonance_min,
            resonance_max: self.resonance_max,
        }
    }

    crate::builder_setters! {
    name: String,
    body_min: i32,
    body_max: i32,
    agility_min: i32,
    agility_max: i32,
    reaction_min: i32,
    reaction_max: i32,
    strength_min: i32,
    strength_max: i32,
    willpower_min: i32,
    willpower_max: i32,
    logic_min: i32,
    logic_max: i32,
    intuition_min: i32,
    intuition_max: i32,
    charisma_min: i32,
    charisma_max: i32,
    edge_min: i32,
    edge_max: i32,
    magical_type: MagicalType,
    magic_min: i32,
    magic_max: i32,
    resonance_min: i32,
    resonance_max: i32,
    }
}
